version: '3.7'

services:
  keycloak:
    image: jboss/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin  # Replace with your Keycloak admin username
      - KEYCLOAK_PASSWORD=admin  # Replace with your Keycloak admin password
      - DB_VENDOR=postgres
      - DB_ADDR=keycloak-postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak_password
    ports:
      - "8080:8080"  # Expose port 8080 for accessing Keycloak
    depends_on:
      - keycloak-postgres
    networks:
      - keycloak-network

  keycloak-postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak_password
      - POSTGRES_DB=keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
