version: "3.8"

services:
  konga:
    image: pantsel/konga
    container_name: konga
    restart: always
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
    networks:
      - zeroguard-net

  kong:
    image: kong:3.4
    container_name: kong
    restart: always
    networks:
      - zeroguard-net
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/etc/kong/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
    volumes:
      - /home/omar/zero_guard/Docker/Kong_API_Gateway/kong.yml:/etc/kong/kong.yml

    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      retries: 3
      start_period: 10s

networks:
  zeroguard-net:
    external: true

