_format_version: "3.0"

services:
  - name: hello-service
    url: http://hello-world:5678
    routes:
      - name: hello-route
        paths:
          - /api/hello
        strip_path: false
        plugins:
          - name: openid-connect
            config:
              issuer: http://keycloak:8080/realms/zerotrust
              auth_methods:
                - bearer
              bearer_jwt_auth_enable_hs_signatures: false
