services:
  hello-world:
    image: hashicorp/http-echo
    command: ["-text=👋 Hello from Kong Zero Trust setup!"]
    ports:
      - "9000:5678"
    networks:
      - zeroguard-net

networks:
  zeroguard-net:
    driver: bridge

