---
- name: Configure SELinux Booleans
  hosts: linux_server
  become: true

  tasks:
    - name: Set Required SELinux Booleans
      ansible.builtin.seboolean:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        persistent: yes
      loop:
        - { name: "httpd_can_network_connect", state: "yes" }
        - { name: "nis_enabled", state: "yes" }
        - { name: "samba_domain_controller", state: "yes" }
        - { name: "authlogin_nsswitch_use_ldap", state: "yes" }
        - { name: "allow_ypbind", state: "yes" }
        - { name: "ssh_keysign", state: "yes" }
        - { name: "logrotate_read_inside_containers", state: "yes" }
        - { name: "cron_can_relabel", state: "yes" }

    - name: All SELinux booleans have been set successfully.
      debug:
        msg: "[!] All SELinux booleans were set without errors."
