---
- name: Deploy Kong on PEP Host
  hosts: pep
  become: yes
  vars:
    deploy_dir: "/opt/zero_guard"          
    compose_file: "docker-compose.yml" 
  tasks:
    - name: Ensure deployment directory exists
      file:
        path: "{{ deploy_dir }}"
        state: directory
        mode: '0755'

    - name: Run Docker Compose to deploy/update Kong
      command: docker-compose -f {{ compose_dir }}/{{ compose_file }} up -d
      args:
        chdir: "{{ deploy_dir }}"
      register: compose_output

    - name: Show Docker Compose output
      debug:
        var: compose_output.stdout
