---
- name: Install and configure FreeIPA
  hosts: ipa_servers
  become: true
  vars:
    ipa_domain: "linuxserver"  
    ipa_realm: "linuxserver"   
    

  tasks:
    - name: Ensure necessary repositories are present
      package:
        name: "{{ item }}"
        state: present
      loop:
        - ipa-server
        - ipa-server-dns
        - bind
        - bind-utils

    - name: Set the server hostname
      hostname:
        name: "{{ ipa_server_hostname }}"

    - name: Install FreeIPA server
      command: ipa-server-install --domain={{ ipa_domain }} --realm={{ ipa_realm }} --admin-password={{ ipa_admin_password }} --no-ntp --unattended

    - name: Start and enable FreeIPA services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - ipa
        - ipa-dns
        - ipa-ods

    - name: Configure firewall to allow FreeIPA ports
      firewalld:
        service: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - freeipa
        - dns
        - http
        - https

    - name: Ensure DNS is configured correctly (if using DNS)
      command: ipa dnsconfig-mod --forwarders=<your_forwarder_ip>
      when: ipa_dns is defined and ipa_dns == true

    - name: Test FreeIPA server installation
      command: ipa user-find admin
      register: ipa_user_find
      failed_when: ipa_user_find.rc != 0
      changed_when: false
