all:
  hosts:
    linux_server:
      ansible_host: 192.168.2.129
      ansible_user: linuxserver
      
    

    logging_server:
      ansible_host: 192.168.3.129
      ansible_user: logging
      

    
