all:
  hosts:
    linux_server:
      ansible_host: 192.168.2.129
      ansible_user: linuxserver
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_become: true
      ansible_become_method: sudo

    logging_server:
      ansible_host: 192.168.3.129
      ansible_user: logging
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_become: true
      ansible_become_method: sudo