- name: Deploy Keycloak Docker Compos
  hosts: localhost
  become: false

  vars:
    docker_compose_path: "/home/omar/zero_guard/Docker/Keycloak/docker-compose.yml"
    secrets: {}

  tasks:
    - name: Stop and remove existing Kong containers
      shell: docker-compose down --remove-orphans
      args:
        chdir: "{{ docker_compose_path | dirname }}"
      ignore_errors: true

    - name: Prune unused Docker resources (but keep named volumes)
      shell: docker system prune -f
      ignore_errors: true

    - name: Start Keycloak with Docker Compose
      shell: docker-compose up -d --remove-orphans
      args:
        chdir: "{{ docker_compose_path | dirname }}"
    
