---
- name: Manage Keycloak Docker Compose
  hosts: pdp
  become: yes

  vars:
    local_compose_path: /home/control_node/Desktop/zero_guard/Docker/Keycloak
    remote_compose_path: /home/zeroguard/ansible/keycloak


  tasks:
    - name: Check if Docker is already installed
      command: which docker
      register: docker_check
      ignore_errors: true

    - name: Install Docker if not present
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: docker_check.rc != 0


    - name: Ensure target directory exists on PEP VM
      file:
        path: /opt/keycloak
        state: directory
        mode: '0755'

    - name: Copy Keycloak files to remote PDP VM
      copy:
        src: ../Docker/Keycloak
        dest: /opt/keycloak
        mode: '0644'
        directory_mode: '0755'
        force: yes

    - name: Run Docker Compose
      community.docker.docker_compose:
        project_src: "{{ remote_compose_path }}"
        files:
          - docker-compose.yml
          