---
- name: Manage Keycloak Docker Compos
  hosts: pdp
  become: yes

  vars:
    local_compose_path: /home/control_node/Desktop/zero_guard/Docker/Keycloak
    remote_compose_path: /opt/keycloak


  tasks:
    - name: Check if Docker is already installed
      command: which docker
      register: docker_check
      ignore_errors: true

    - name: Install Docker if not present
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: docker_check.rc != 0


    - name: Ensure target directory exists on PEP VM
      file:
        path: "{{ remote_compose_path }}"
        state: directory
        mode: '0755'

    - name: Overwrite Docker Compose and Kong config on PEP VM
      copy:
        src: "{{ local_compose_path }}/"
        dest: "{{ remote_compose_path }}/"
        mode: '0644'
        directory_mode: '0755'
        force: yes
        remote_src: no

    # - name: Stop and remove all containers before deploying
    #   command: docker-compose down --remove-orphans
    #   args:
    #     chdir: "{{ remote_compose_path }}"

    - name: Run Docker Compose
      community.docker.docker_compose:
        project_src: "{{ remote_compose_path }}"
        files:
          - docker-compose.yml
          