---
- name: Manage Keycloak Docker Compose
  hosts: pdp
  become: yes

  vars:
    local_compose_path: /home/control_node/Desktop/zero_guard/Docker/Keycloak
    remote_compose_path: /opt/keycloak


  tasks:
    - name: Check if Docker is already installed
      command: which docker
      register: docker_check
      ignore_errors: true

    - name: Install Docker if not present
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: docker_check.rc != 0


    - name: Ensure target directory exists on PEP VM
      file:
        path: "{{ remote_compose_path }}"
        state: directory
        mode: '0755'

    - name: Overwrite Docker Compose and Kong config on PEP VM
      copy:
        src: "{{ local_compose_path }}/"
        dest: "{{ remote_compose_path }}/"
        mode: '0644'
        directory_mode: '0755'
        force: yes
        remote_src: no

    - name: Stop and remove existing Kong container if it exists
      docker_container:
        name: kong
        state: absent  # This will stop and remove the container if it exists
      ignore_errors: true  # Ignore errors in case the container doesn't exist

    - name: Stop and remove all containers before deploying on the target machine
      command: docker-compose down --remove-orphans
      args:
        chdir: "{{ docker_compose_path | dirname }}"
      ignore_errors: true  # Ignore errors if there are no running containers

    - name: Run Docker Compose
      community.docker.docker_compose:
        project_src: "{{ remote_compose_path }}"
        files:
          - docker-compose.yml
          