- name: Deploy Keycloak Docker Compose
  hosts: localhost
  become: false

  vars:
    docker_compose_path: "C:/Users/omhg2/OneDrive/Desktop/ZeroGuard/zero_guard/Docker/Keycloak/docker-compose.yml"
  
  tasks:
    - name: Stop and remove existing containers (if any)
      command: docker-compose -f {{ docker_compose_path }} down --remove-orphans
      args:
        chdir: "{{ docker_compose_path | dirname }}"
      ignore_errors: true

    - name: Prune unused Docker resources (safe cleanup)
      win_shell: docker system prune -f
      ignore_errors: true

    - name: Deploy Keycloak & Postgres with Docker Compose
      command: docker-compose -f {{ docker_compose_path }} up -d --remove-orphans
      args:
        chdir: "{{ docker_compose_path | dirname }}"