---
- name: Manage Docker Compose deployment
  hosts: pep
  become: yes  # Run tasks with elevated privileges

  vars:
    local_compose_path: /home/control_node/Desktop/zero_guard/Docker/Kong_API_Gateway
    remote_compose_path: /home/ansible/kong


  tasks:
    - name: Check if Docker is already installed
      command: which docker
      register: docker_check
      ignore_errors: true

    - name: Install Docker if not present
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: docker_check.rc != 0

    # - name: Install Docker Compose
    #   shell: |
    #     curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    #     chmod +x /usr/local/bin/docker-compose
    #   args:
    #     executable: /bin/bash

  
    - name: Copy Kong API Gateway files to remote VM
      copy:
        src: "{{ local_compose_path }}/"
        dest: "{{ remote_compose_path }}/"
        owner: pep
        group: pep
        mode: 0755

    - name: Run Docker Compose stack
      community.docker.docker_compose:
        project_src: "{{ remote_compose_path }}"
        files:
          - docker-compose.yml
          