- name: Deploy Kong on PEP Host
  hosts: pep
  become: yes
  vars:
    deploy_dir: "/opt/zero_guard/kong"
    local_compose_dir: "Docker/Kong_API_Gateway"
    compose_file: "docker-compose.yml"

  tasks:
    - name: Ensure base directory on remote
      file:
        path: "{{ deploy_dir }}"
        state: directory
        mode: '0755'

    - name: Copy Docker Compose folder to remote
      synchronize:
        src: "{{ local_compose_dir }}/"
        dest: "{{ deploy_dir }}/Docker/Kong_API_Gateway/"
        delete: yes
        archive: yes
        recursive: yes
        mode: push               # Push files from local to remote
      delegate_to: localhost     # Execute rsync on the control node

    - name: Run Docker Compose to deploy/update Kong
      command: docker-compose -f "{{ deploy_dir }}/Docker/Kong_API_Gateway/{{ compose_file }}" up -d
      args:
        chdir: "{{ deploy_dir }}/Docker/Kong_API_Gateway"
      register: compose_output

    - name: Show Docker Compose output
      debug:
        var: compose_output.stdout
