---
- name: Manage Docker Compose deployment
  hosts: pep
  become: yes

  vars:
    local_compose_path: /home/control_node/Desktop/zero_guard/Docker/Kong_API_Gateway
    remote_compose_path: /home/zeroguard/ansible/kong


  tasks:
    - name: Check if Docker is already installed
      command: which docker
      register: docker_check
      ignore_errors: true

    - name: Ensure target directory exists on PEP VM
      file:
        path: /opt/kong
        state: directory
        mode: '0755'

    - name: Copy Docker Compose and Kong config to PEP VM
      copy:
        src: ../Docker/Kong_API_Gateway/
        dest: /opt/kong/
        mode: '0644'
        directory_mode: '0755'

    - name: Run Docker Compose to deploy Kong
      ansible.builtin.shell: docker compose up -d
      args:
        chdir: /opt/kong
      register: kong_output
      failed_when: kong_output.rc != 0 and '"Error"' in kong_output.stderr
          