- name: Deploy Kong Docker Compose
  hosts: localhost
  become: false

  vars:
    docker_compose_path: "/home/omar/zero_guard/Docker/Kong_API_Gateway/docker-compose.yml"
    kong_config_path: "/home/omar/zero_guard/Docker/Kong_API_Gateway/kong.yml"

  tasks:
    - name: Stop and remove existing Kong containers
      command: docker-compose down --remove-orphans
      args:
        chdir: "{{ docker_compose_path | dirname }}"
      ignore_errors: true

    - name: Prune unused Docker resources (but keep named volumes)
      shell: docker system prune -f
      ignore_errors: true

    - name: Start Kong API Gateway with Docker Compose
      command: docker-compose up -d --remove-orphans
      args:
        chdir: "{{ docker_compose_path | dirname }}"