- name: Minimal Docker Compose Playbook
  hosts: pep
  become: yes

  tasks:
    - name: Run Docker Compose
      command: docker-compose -f /home/pep/Desktop/zero_guard/Docker/Kong_API_Gateway/docker-compose.yml up -d
      
