name: Run the Pipeline

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: self-hosted

    env:
      INVENTORY: '/home/omar/zero_guard/Ansible/inventory.yml'
      KONG_PLAYBOOK: '/home/omar/zero_guard/Ansible/kong_playbook.yml'
      KEYCLOAK_PLAYBOOK: '/home/omar/zero_guard/Ansible/keycloak_playbook.yml'
      OPA_PLAYBOOK: '/home/omar/zero_guard/Ansible/opa_playbook.yml'
      PROJECT_DIRECTORY: '/home/omar/zero_guard' 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Pull latest code changes
        shell: bash
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        run: |
          git pull origin main || true


      - name: Run Kong Container
        shell: bash
        run: |
          ansible-playbook -i ${{ env.INVENTORY}} ${{ env.KONG_PLAYBOOK}}

      - name: Run Keycloak Container
        shell: bash
        run: |
          ansible-playbook -i ${{ env.INVENTORY}} ${{ env.KEYCLOAK_PLAYBOOK}}
