name: Run the Pipeline

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: self-hosted

    env:
      INVENTORY: ${{ secrets.INVENTORY}}
      KONG_PLAYBOOK: ${{ secrets.KONG_PLAYBOOK_PATH}}
      KEYCLOAK_PLAYBOOK: ${{ secrets.KEYCLOAK_PLAYBOOK_PATH}}
      OPA_PLAYBOOK: ${{ secrets.OPA_PLAYBOOK_PATH}}
      PROJECT_DIRECTORY: ${{ secrets.PROJECT_DIRECTORY}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Pull latest code changes
        shell: bash
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        run: |
          git pull origin main || true

      - name: Run Kong Container
        shell: bash
        run: |
          ansible-playbook -i ${{ env.INVENTORY}} ${{ env.KONG_PLAYBOOK}}

      - name: Run Keycloak Container
        shell: bash
        run: |
          ansible-playbook -i ${{ env.INVENTORY}} ${{ env.KEYCLOAK_PLAYBOOK}}

      - name: Run OPA Container
        shell: bash
        run: |
          ansible-playbook -i ${{ env.INVENTORY}} ${{ env.OPA_PLAYBOOK}}
