name: Run the Pipeline

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: self-hosted
    
    env:
      INVENTORY: 'inventory.yml'
      KONG_PLAYBOOK: 'kong_playbook.yml'
      KEYCLOAK_PLAYBOOK: 'keycloak_playbook.yml'
      OPA_PLAYBOOK: 'opa_playbook.yml'
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Pull latest code changes
        run: |
          git pull origin main
        working-directory: ${{ secrets.PROJECT_DIRECTORY }}
        continue-on-error: true

      - name: Run Kong Container
        shell: bash
        run: |
          docker-compose -f "/c/Users/omhg2/OneDrive/Desktop/ZeroGuard/zero_guard/Docker/Kong_API_Gateway/docker-compose.yml" up -d
       
        

      # - name: Run Ansible Playbook to Deploy Keycloak
      #   working-directory: Ansible
      #   run: |
      #     ansible-playbook -i ${INVENTORY} ${KEYCLOAK_PLAYBOOK}
      #   env:
      #     PDP_SUDO_PASS: ${{ secrets.PDP_SUDO_PASS }}
        
      # - name: Run Ansible Playbook to Deploy OPA
      #   working-directory: Ansible
      #   run: |
      #     ansible-playbook -i ${INVENTORY} ${OPA_PLAYBOOK}
      #   env:
      #     PDP_SUDO_PASS: ${{ secrets.PDP_SUDO_PASS }}
