name: Run the Pipeline

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: self-hosted
    
    env:
      INVENTORY: 'inventory.yml'
      KONG_PLAYBOOK: 'kong_playbook.yml'
      KEYCLOAK_PLAYBOOK: 'keycloak_playbook.yml'
      PEP_SUDO_PASS: ${{ secrets.PEP_SUDO_PASS }}
      PDP_SUDO_PASS: ${{ secrets.PDP_SUDO_PASS }}


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Pull latest code changes
        run: |
          git pull origin main
        working-directory: /home/control_node/Desktop/zero_guard  
        continue-on-error: true

      # - name: Run Ansible Playbook to Deploy Kong
      #   working-directory: Ansible
      #   run: |
      #     ansible-playbook -i ${INVENTORY} ${KONG_PLAYBOOK} --extra-vars "ansible_become_pass=${PEP_SUDO_PASS}"
      #   env:
      #     PEP_SUDO_PASS: ${{ secrets.PEP_SUDO_PASS }}
        

      - name: Run Ansible Playbook to Deploy Keycloak
        working-directory: Ansible
        run: |
          ansible-playbook -i ${INVENTORY} ${KEYCLOAK_PLAYBOOK} --extra-vars "ansible_become_pass=${PDP_SUDO_PASS}"
        env:
          PDP_SUDO_PASS: ${{ secrets.PDP_SUDO_PASS }}
        
