name: Deploy Kong via Control Node

on:
  push:
    branches:
      - main

jobs:
  deploy-kong:
    runs-on: self-hosted
    
    env:
      INVENTORY: 'inventory.yml'
      PLAYBOOK: 'kong_playbook.yml'
      SUDO_PASS: ${{ secrets.PEP_SUDO_PASS }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Ansible Playbook to Deploy Kong
        working-directory: Ansible
        run: |
          ansible-playbook -i ${INVENTORY} ${PLAYBOOK} --extra-vars "ansible_become_pass=${PEP_SUDO_PASS}"
