name: Run the Pipeline

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: self-hosted

    env:
      INVENTORY: 'Ansible/inventory.yml'
      KONG_PLAYBOOK: 'Ansible/kong_playbook.yml'
      KEYCLOAK_PLAYBOOK: 'Ansible/keycloak_playbook.yml'
      OPA_PLAYBOOK: 'Ansible/opa_playbook.yml'
      PROJECT_DIRECTORY: '/home/omar/zero_guard' 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Pull latest code changes
        shell: bash
        working-directory: ${{ env.PROJECT_DIRECTORY }}
        run: |
          git pull origin main || true


      - name: Run Kong Container
        shell: bash
        run: |
          docker-compose -f "/home/omar/zero_guard/Docker/Kong_API_Gateway/docker-compose.yml" up -d

      # - name: Activate Python Virtual Environment
      #   shell: bash
      #   run: |
      #     source "${PROJECT_DIRECTORY}/ansible-env/bin/activate"

      # - name: Run Keycloak Ansible Playbook
      #   shell: bash
      #   working-directory: ${{ env.PROJECT_DIRECTORY }}
      #   run: |
      #     source ansible-env/bin/activate
      #     ansible-playbook -i $INVENTORY $KEYCLOAK_PLAYBOOK

      # - name: Run OPA Ansible Playbook
      #   shell: bash
      #   working-directory: ${{ env.PROJECT_DIRECTORY }}
      #   run: |
      #     source ansible-env/bin/activate
      #     ansible-playbook -i $INVENTORY $OPA_PLAYBOOK
